# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '0.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(255, 198)
        MainWindow.setMinimumSize(QtCore.QSize(255, 198))
        MainWindow.setMaximumSize(QtCore.QSize(255, 198))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.subjectComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.subjectComboBox.setEditable(False)
        self.subjectComboBox.setProperty("currentText", "")
        self.subjectComboBox.setObjectName("subjectComboBox")
        self.verticalLayout_3.addWidget(self.subjectComboBox)
        self.roleGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.roleGroup.setObjectName("roleGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.roleGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.roleStudent = QtWidgets.QRadioButton(self.roleGroup)
        self.roleStudent.setChecked(True)
        self.roleStudent.setObjectName("roleStudent")
        self.verticalLayout_2.addWidget(self.roleStudent)
        self.roleTeacher = QtWidgets.QRadioButton(self.roleGroup)
        self.roleTeacher.setObjectName("roleTeacher")
        self.verticalLayout_2.addWidget(self.roleTeacher)
        self.verticalLayout_3.addWidget(self.roleGroup)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_3.addWidget(self.startButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помощник ЕГЭ"))
        self.subjectComboBox.setProperty("placeholderText", _translate("MainWindow", "Предмет"))
        self.roleGroup.setTitle(_translate("MainWindow", "Роль"))
        self.roleStudent.setText(_translate("MainWindow", "Ученик"))
        self.roleTeacher.setText(_translate("MainWindow", "Учитель"))
        self.startButton.setText(_translate("MainWindow", "Начать"))
