# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.Tasks = QtWidgets.QWidget()
        self.Tasks.setGeometry(QtCore.QRect(0, 0, 780, 531))
        self.Tasks.setObjectName("Tasks")
        self.scrollArea.setWidget(self.Tasks)
        self.verticalLayout.addWidget(self.scrollArea)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createPDFButton = QtWidgets.QPushButton(self.widget)
        self.createPDFButton.setObjectName("createPDFButton")
        self.horizontalLayout.addWidget(self.createPDFButton)
        self.finishButton = QtWidgets.QPushButton(self.widget)
        self.finishButton.setObjectName("finishButton")
        self.horizontalLayout.addWidget(self.finishButton)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Тестирование"))
        self.createPDFButton.setText(_translate("Form", "Создать PDF"))
        self.finishButton.setText(_translate("Form", "Завершить"))
